### ISSUE TITLE
Create an html and json file for every rule

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#33] opened 2019-10-10 08:07 UTC
Like in the original sonar-java project, we should have an html file for every rule, where we describe the rule and show one example each for compliant and noncompliant code.

Additionally, we should hava a json for every rule as well.

**Comment by hohwille** [comment] 2019-10-15 07:55
More or less a duplicate of #15

**Closed** 2019-10-23 14:55 UTC
Labels: enhancement
