### ISSUE TITLE
Project analysis fails and throws Nullpointer

### ISSUE THREAD

**Issue by isandesh1986** [devonfw/sonar-devon4j-plugin#118] opened 2020-12-14 13:34 UTC
### Expected behavior
As a developer, I want to do a mvn sonar build on my application project so that I can analyze and fix the issues shown by sonar report.

### Actual behavior
mvn sonar:sonar build of mythaistar fails with NullPointerException.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  After building mvn clean install in MyThaiStar application, execute mvn sonar:sonar -Dsonar.login=<<token>>
NullPointerException occurs at https://github.com/devonfw/sonar-devon4j-plugin/blob/c562a9211274ed9ea6ad045e6b69700742f1a93d/src/main/java/com/devonfw/ide/sonarqube/common/impl/SonarDevon4jPlugin.java#L66

**Exception log pasted here:-** 
Caused by: java.lang.NullPointerException
    at java.util.Objects.requireNonNull (Objects.java:221)
    at java.util.Arrays$ArrayList.<init> (Arrays.java:4323)
    at java.util.Arrays.asList (Arrays.java:4310)
    at com.devonfw.ide.sonarqube.common.impl.SonarDevon4jPlugin.getPlugins (SonarDevon4jPlugin.java:66)
    at com.devonfw.ide.sonarqube.common.impl.SonarDevon4jPlugin.hasPlugin (SonarDevon4jPlugin.java:73)
    at com.devonfw.ide.sonarqube.common.impl.SonarDevon4jPlugin.lambda$getMissingPlugins$2 (SonarDevon4jPlugin.java:105)
    at java.util.Arrays$ArrayList.forEach (Arrays.java:4390)
    at com.devonfw.ide.sonarqube.common.impl.SonarDevon4jPlugin.getMissingPlugins (SonarDevon4jPlugin.java:104)
    at com.devonfw.ide.sonarqube.common.impl.SonarDevon4jPlugin.define (SonarDevon4jPlugin.java:51)

**Comment by lmarniazman** [comment] 2020-12-17 01:36
The NPE issue should be resolved with PR #120

However, there seems to be a general problem with `findbugs`. I am getting the following exception when running an analysis with `findbugs` installed: 

![findbugs_error](https://user-images.githubusercontent.com/49903872/102426922-98ac1180-4010-11eb-90b6-e6fddda2fdf5.jpg)

**Comment by hohwille** [comment] 2020-12-17 15:03
IMHO the `File[] fileList` was `null` because the scanned directory did not exist as described in PR #120.
So with PR #120 we have the NPE fixed. However, if the extensions/plugins directory is wrong, we will still not find any plugins and our product is still buggy/broken. Can we retest this and do further analysis what the value of `this.pluginDirectory` actually is and what should have been the correct value of that directory on the local disk?

**Comment by hohwille** [comment] 2020-12-17 15:06
IMHO this code:
https://github.com/lmarniazman/sonar-devon4j-plugin/blob/6c2a38554d8e0bb8f60422d12fd1cd8d06d609bd/src/main/java/com/devonfw/ide/sonarqube/common/impl/SonarDevon4jPlugin.java#L45

Was just a best guess but is not properly correct. Depending on where and how you launch SonarQube this may work or may not work. If you launch SonarQube from within the `bin` directory then the extensions would be searched below this `bin` directory what is obviously wrong.

**Comment by hohwille** [comment] 2020-12-17 15:41
My assumption for the reason of the error was wrong. The problem ist that the `SonarDevon4jPlugin` class gets also executed during *analysis* with our plugin. In that case there is no sonarqube server in the current directory but the project to analyse. With fixing the NPE by PR #120 we solve this problem as the analysis can now proceed.
To detect if we are in analysis or running in the server and doing some things smarter we will file a new issue. I can therefore close this issue again.

**Closed by hohwille** 2020-12-17 15:41 UTC
Labels: bug
